#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
using LogKit = StellarFramework.SingletonKitDiagnostics;

namespace StellarFramework.Editor
{
    public class SingletonGenerator : IPreprocessBuildWithReport
    {
        private const string OptionalAddressablesRuntimeAssemblyName = "StellarFramework.ResKit.Addressables";
        public const string GeneratedDirectory = "Assets/Generated/StellarFramework/SingletonRegister";
        public const string GeneratedFilePath = GeneratedDirectory + "/SingletonRegister.cs";

        public int callbackOrder => 0;

        public static void ScheduleAutomaticGeneration()
        {
            EditorApplication.delayCall -= QueueGenerationAfterReload;
            EditorApplication.delayCall += QueueGenerationAfterReload;
        }

        private static void QueueGenerationAfterReload()
        {
            EditorApplication.delayCall -= GenerateAfterScriptsReload;
            EditorApplication.delayCall += GenerateAfterScriptsReload;
        }

        private static void GenerateAfterScriptsReload()
        {
            if (EditorApplication.isCompiling || EditorApplication.isUpdating)
            {
                EditorApplication.delayCall -= GenerateAfterScriptsReload;
                EditorApplication.delayCall += GenerateAfterScriptsReload;
                return;
            }

            try
            {
                GenerateInternal(false);
            }
            catch (Exception exception)
            {
                Debug.LogError(
                    "[SingletonGenerator] 脚本重载后自动生成失败。请修复错误后重新编译或通过 ToolsHub 手动生成。\n" +
                    exception);
            }
        }

        /// <summary>
        /// 挂载构建前置钩子，确保打出的包一定包含最新的单例注册表。
        /// </summary>
        public void OnPreprocessBuild(BuildReport report)
        {
            LogKit.Log("[SingletonGenerator] 构建前自动生成单例注册表...");
            Generate();
        }

        public static void Generate()
        {
            GenerateInternal(true);
        }

        private static bool GenerateInternal(bool logWhenUnchanged)
        {
            List<Type> types = GetSingletonTypes()
                .Where(type => type != null)
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToList();

            StringBuilder sb = new StringBuilder(8192);
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("// Auto-generated by StellarFramework.SingletonGenerator");
            sb.AppendLine("// 职责：在游戏启动前将单例元数据与纯 C# 单例创建器注入工厂，消除运行时反射。");
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using StellarFramework;");
            sb.AppendLine();
            sb.AppendLine("namespace StellarFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class SingletonRegister");
            sb.AppendLine("    {");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        private static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            SingletonFactory.ClearMetadata();");
            sb.AppendLine("            SingletonFactory.ClearPureSingletonCreators();");

            int metadataCount = 0;
            int creatorCount = 0;

            foreach (Type type in types)
            {
                if (type == null)
                {
                    continue;
                }

                if (type.IsAbstract || type.IsGenericTypeDefinition)
                {
                    continue;
                }

                SingletonAttribute attr = type.GetCustomAttribute<SingletonAttribute>();
                if (attr == null)
                {
                    continue;
                }

                if (ShouldSkipType(type))
                {
                    continue;
                }

                string typeName = GetCSharpTypeName(type);
                if (string.IsNullOrEmpty(typeName))
                {
                    Debug.LogError($"[SingletonGenerator] 跳过非法类型: FullName 为空, Type={type.Name}");
                    continue;
                }

                string resPath = string.IsNullOrEmpty(attr.ResourcePath)
                    ? "\"\""
                    : $"\"{attr.ResourcePath.Replace("\\", "/")}\"";

                string lifeCycle = $"SingletonLifeCycle.{attr.LifeCycle}";
                string useContainer = attr.UseContainer ? "true" : "false";

                sb.AppendLine(
                    $"            SingletonFactory.RegisterMetadata(typeof({typeName}), new SingletonMetadata {{ ResourcePath = {resPath}, LifeCycle = {lifeCycle}, UseContainer = {useContainer} }});");
                metadataCount++;

                if (typeof(MonoBehaviour).IsAssignableFrom(type))
                {
                    continue;
                }

                if (type.GetConstructor(Type.EmptyTypes) == null)
                {
                    Debug.LogError($"[SingletonGenerator] 纯 C# 单例缺少无参构造，无法生成创建器: Type={typeName}");
                    continue;
                }

                sb.AppendLine(
                    $"            SingletonFactory.RegisterPureSingletonCreator(typeof({typeName}), static () => new {typeName}());");
                creatorCount++;
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string generatedSource = sb.ToString();
            if (File.Exists(GeneratedFilePath))
            {
                string existing = File.ReadAllText(GeneratedFilePath, Encoding.UTF8);
                if (string.Equals(existing, generatedSource, StringComparison.Ordinal))
                {
                    if (logWhenUnchanged)
                    {
                        LogKit.Log(
                            $"[SingletonGenerator] 静态注册表已是最新版本, Metadata={metadataCount}, PureCreator={creatorCount}, Path={GeneratedFilePath}");
                    }

                    return false;
                }
            }

            if (!Directory.Exists(GeneratedDirectory))
            {
                Directory.CreateDirectory(GeneratedDirectory);
            }

            File.WriteAllText(
                GeneratedFilePath,
                generatedSource,
                new UTF8Encoding(false));
            AssetDatabase.ImportAsset(
                GeneratedFilePath,
                ImportAssetOptions.ForceUpdate);

            LogKit.Log(
                $"[SingletonGenerator] 静态注册表生成完毕, Metadata={metadataCount}, PureCreator={creatorCount}, Path={GeneratedFilePath}");
            return true;
        }

        private static string GetCSharpTypeName(Type type)
        {
            return type?.FullName?.Replace('+', '.');
        }

        private static bool ShouldSkipType(Type type)
        {
            string namespaceName = type.Namespace ?? string.Empty;
            string assemblyName = type.Assembly.GetName().Name ?? string.Empty;
            return string.Equals(assemblyName, OptionalAddressablesRuntimeAssemblyName, StringComparison.Ordinal) ||
                   namespaceName.StartsWith("StellarFramework.Examples", StringComparison.Ordinal) ||
                   string.Equals(type.FullName, "StellarFramework.UI.UIStackManager", StringComparison.Ordinal);
        }

        private static IEnumerable<Type> GetSingletonTypes()
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(GetLoadableTypes)
                .Where(type => type != null && type.GetCustomAttribute<SingletonAttribute>() != null);
        }

        private static IEnumerable<Type> GetLoadableTypes(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException exception)
            {
                return exception.Types.Where(type => type != null);
            }
        }
    }
}
#endif
