using System;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace StellarFramework.Editor
{
    public class SingletonGenerator : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        /// <summary>
        /// 挂载构建前置钩子，确保打出的包一定包含最新的单例注册表。
        /// </summary>
        public void OnPreprocessBuild(BuildReport report)
        {
            LogKit.Log("[SingletonGenerator] 构建前自动生成单例注册表...");
            Generate();
        }

        [MenuItem("StellarFramework/Tools/Generate Singleton Register")]
        public static void GenerateMenu()
        {
            Generate();
        }

        public static void Generate()
        {
            var types = TypeCache.GetTypesWithAttribute<SingletonAttribute>();

            StringBuilder sb = new StringBuilder(8192);
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("// Auto-generated by StellarFramework.SingletonGenerator");
            sb.AppendLine("// 职责：在游戏启动前将单例元数据与纯 C# 单例创建器注入工厂，消除运行时反射。");
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using StellarFramework;");
            sb.AppendLine();
            sb.AppendLine("namespace StellarFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class SingletonRegister");
            sb.AppendLine("    {");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        private static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            SingletonFactory.ClearMetadata();");
            sb.AppendLine("            SingletonFactory.ClearPureSingletonCreators();");

            int metadataCount = 0;
            int creatorCount = 0;

            foreach (Type type in types)
            {
                if (type == null)
                {
                    continue;
                }

                if (type.IsAbstract || type.IsGenericTypeDefinition)
                {
                    continue;
                }

                SingletonAttribute attr = type.GetCustomAttribute<SingletonAttribute>();
                if (attr == null)
                {
                    continue;
                }

                string typeName = type.FullName;
                if (string.IsNullOrEmpty(typeName))
                {
                    Debug.LogError($"[SingletonGenerator] 跳过非法类型: FullName 为空, Type={type.Name}");
                    continue;
                }

                string resPath = string.IsNullOrEmpty(attr.ResourcePath)
                    ? "\"\""
                    : $"\"{attr.ResourcePath.Replace("\\", "/")}\"";

                string lifeCycle = $"SingletonLifeCycle.{attr.LifeCycle}";
                string useContainer = attr.UseContainer ? "true" : "false";

                sb.AppendLine(
                    $"            SingletonFactory.RegisterMetadata(typeof({typeName}), new SingletonMetadata {{ ResourcePath = {resPath}, LifeCycle = {lifeCycle}, UseContainer = {useContainer} }});");
                metadataCount++;

                if (typeof(MonoBehaviour).IsAssignableFrom(type))
                {
                    continue;
                }

                if (type.GetConstructor(Type.EmptyTypes) == null)
                {
                    Debug.LogError($"[SingletonGenerator] 纯 C# 单例缺少无参构造，无法生成创建器: Type={typeName}");
                    continue;
                }

                sb.AppendLine(
                    $"            SingletonFactory.RegisterPureSingletonCreator(typeof({typeName}), static () => new {typeName}());");
                creatorCount++;
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string dir = "Assets/StellarFramework/Generated";
            if (!System.IO.Directory.Exists(dir))
            {
                System.IO.Directory.CreateDirectory(dir);
            }

            string filePath = $"{dir}/SingletonRegister.cs";
            System.IO.File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            LogKit.Log(
                $"[SingletonGenerator] 静态注册表生成完毕, Metadata={metadataCount}, PureCreator={creatorCount}, Path={filePath}");
        }
    }
}