// ==================================================================================
// SingletonGenerator - Commercial Convergence V2
// ----------------------------------------------------------------------------------
// 职责：在编译期扫描所有 [Singleton] 特性，生成静态注册代码。
// 彻底消除运行时的反射开销。包含手动触发菜单与构建前自动触发钩子。
// ==================================================================================

using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace StellarFramework.Editor
{
    public class SingletonGenerator : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        /// <summary>
        /// 挂载构建前置钩子，确保打出的包一定包含最新的单例注册表
        /// </summary>
        public void OnPreprocessBuild(BuildReport report)
        {
            LogKit.Log("[SingletonGenerator] 构建前自动生成单例注册表...");
            Generate();
        }

        [MenuItem("StellarFramework/Tools/Generate Singleton Register")]
        public static void GenerateMenu()
        {
            Generate();
        }

        public static void Generate()
        {
            // 利用 Unity 内部的 TypeCache 极速获取，无需遍历所有 Assembly
            var types = TypeCache.GetTypesWithAttribute<SingletonAttribute>();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("// Auto-generated by StellarFramework.SingletonGenerator");
            sb.AppendLine("// 职责：在游戏启动前将单例元数据注入工厂，消除运行时反射。");
            sb.AppendLine("// ==================================================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using StellarFramework;");
            sb.AppendLine();
            sb.AppendLine("namespace StellarFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class SingletonRegister");
            sb.AppendLine("    {");
            sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        private static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            SingletonFactory.ClearMetadata();");

            int count = 0;
            foreach (var type in types)
            {
                if (type.IsAbstract || type.IsGenericTypeDefinition) continue;

                var attr = type.GetCustomAttribute<SingletonAttribute>();
                if (attr == null) continue;

                string typeName = type.FullName;
                // 将 \ 替换为 / 防止路径转义错误
                string resPath = string.IsNullOrEmpty(attr.ResourcePath)
                    ? "\"\""
                    : $"\"{attr.ResourcePath.Replace("\\", "/")}\"";
                string lifeCycle = $"SingletonLifeCycle.{attr.LifeCycle}";
                string useContainer = attr.UseContainer.ToString().ToLower();

                sb.AppendLine(
                    $"            SingletonFactory.RegisterMetadata(typeof({typeName}), new SingletonMetadata {{ ResourcePath = {resPath}, LifeCycle = {lifeCycle}, UseContainer = {useContainer} }});");
                count++;
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string dir = "Assets/StellarFramework/Generated";
            if (!System.IO.Directory.Exists(dir))
            {
                System.IO.Directory.CreateDirectory(dir);
            }

            string filePath = $"{dir}/SingletonRegister.cs";
            System.IO.File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();

            LogKit.Log($"[SingletonGenerator] 静态注册表生成完毕，共收录 {count} 个单例。路径: {filePath}");
        }
    }
}